version: 2
  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: '00:00'
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope